import React, { useEffect, useMemo, useState } from "react";
const STORAGE_KEY = "bg-payment-tracker-state-v2";
const EMPTY_STATE = { invoices: [], notes: "" };
const money = value => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value || 0));
const cfg = () => ({ url: import.meta.env.VITE_SUPABASE_URL, key: import.meta.env.VITE_SUPABASE_ANON_KEY });
async function loadCloud(){ const {url,key}=cfg(); const r=await fetch(`${url}/rest/v1/bg_tracker_state?id=eq.default&select=data`,{headers:{apikey:key,Authorization:`Bearer ${key}`}}); if(!r.ok) throw new Error(await r.text()); const j=await r.json(); return j?.[0]?.data||EMPTY_STATE; }
async function saveCloud(data){ const {url,key}=cfg(); const r=await fetch(`${url}/rest/v1/bg_tracker_state?id=eq.default`,{method:'PATCH',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({data})}); if(!r.ok) throw new Error(await r.text()); }
export default function App(){ const [state,setState]=useState(EMPTY_STATE); const [status,setStatus]=useState('Loading cloud data...'); const [loaded,setLoaded]=useState(false); const [form,setForm]=useState({company:'',invoiceNo:'',date:'',amount:'',paid:'',remarks:''});
useEffect(()=>{(async()=>{try{const cloud=await loadCloud(); const merged={...EMPTY_STATE,...cloud,invoices:Array.isArray(cloud.invoices)?cloud.invoices:[]}; setState(merged); localStorage.setItem(STORAGE_KEY,JSON.stringify(merged)); setStatus('Cloud connected');}catch(err){const local=localStorage.getItem(STORAGE_KEY); if(local){setState(JSON.parse(local)); setStatus('Using local backup');} else setStatus(`Cloud failed: ${err.message}`);} finally{setLoaded(true);}})()},[]);
useEffect(()=>{ if(!loaded) return; localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); const t=setTimeout(async()=>{ try{ await saveCloud(state); setStatus('Saved to Supabase'); } catch(err){ setStatus(`Cloud save failed: ${err.message}`); } },700); return ()=>clearTimeout(t); },[state,loaded]);
const totals=useMemo(()=>state.invoices.reduce((a,i)=>{const amt=Number(i.amount||0),paid=Number(i.paid||0); a.amount+=amt; a.paid+=paid; a.pending+=Math.max(0,amt-paid); return a;},{amount:0,paid:0,pending:0}),[state.invoices]);
function addInvoice(e){ e.preventDefault(); if(!form.company||!form.invoiceNo||!form.amount) return; const inv={id:crypto.randomUUID(),company:form.company,invoiceNo:form.invoiceNo,date:form.date||new Date().toISOString().slice(0,10),amount:Number(form.amount||0),paid:Number(form.paid||0),remarks:form.remarks}; setState(s=>({...s,invoices:[inv,...s.invoices]})); setForm({company:'',invoiceNo:'',date:'',amount:'',paid:'',remarks:''}); }
return <main style={{padding:20,fontFamily:'Inter, sans-serif',background:'#f8fafc',minHeight:'100vh'}}><div style={{background:'linear-gradient(135deg,#0f172a,#1d4ed8)',color:'#fff',padding:24,borderRadius:24,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{opacity:.8,fontSize:12,fontWeight:700}}>NH PACKAGE 03 & 04</div><h1 style={{margin:'8px 0'}}>BG Payment Tracker</h1><div>{status}</div></div><button onClick={async()=>{try{const cloud=await loadCloud(); setState(cloud); setStatus('Cloud reloaded');}catch(err){setStatus(err.message)}}} style={{background:'#fff',color:'#111827',border:0,padding:'12px 16px',borderRadius:12,fontWeight:700}}>Retry cloud load</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:16,marginTop:18}}>{[['Total Bills',totals.amount],['Paid',totals.paid],['Pending',totals.pending]].map(([k,v])=><div key={k} style={{background:'#fff',padding:20,borderRadius:20,border:'1px solid #e2e8f0'}}><div style={{color:'#64748b'}}>{k}</div><strong style={{fontSize:26}}>{money(v)}</strong></div>)}</div><form onSubmit={addInvoice} style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:10,marginTop:18,background:'#fff',padding:18,borderRadius:20,border:'1px solid #e2e8f0'}}>{['company','invoiceNo','date','amount','paid','remarks'].map(f=><input key={f} type={f==='date'?'date':f==='amount'||f==='paid'?'number':'text'} placeholder={f} value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})} style={{padding:12,border:'1px solid #cbd5e1',borderRadius:12}} />)}<button type='submit' style={{background:'#2563eb',color:'#fff',border:0,padding:12,borderRadius:12,fontWeight:700}}>Add Invoice</button></form><div style={{background:'#fff',padding:18,borderRadius:20,border:'1px solid #e2e8f0',marginTop:18,overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Date','Company','Invoice','Bill','Paid','Pending','Remarks'].map(h=><th key={h} style={{textAlign:'left',padding:12,borderBottom:'1px solid #e2e8f0'}}>{h}</th>)}</tr></thead><tbody>{state.invoices.map(i=><tr key={i.id}><td style={{padding:12}}>{i.date}</td><td>{i.company}</td><td>{i.invoiceNo}</td><td>{money(i.amount)}</td><td><input type='number' value={i.paid} onChange={e=>setState(s=>({...s,invoices:s.invoices.map(x=>x.id===i.id?{...x,paid:Number(e.target.value||0)}:x)}))} style={{padding:8,border:'1px solid #cbd5e1',borderRadius:10,width:100}} /></td><td>{money(Math.max(0,i.amount-i.paid))}</td><td>{i.remarks}</td></tr>)}</tbody></table></div></main>}
